# TODO tune
CONTEXT_WINDOW_SIZE = 256
BATCH_SIZE = 64
LEARNING_RATE = 3e-4
EPOCHS = int(5e3)
N_ATTENTION_HEADS = 6
FEATURE_DIMS = 384
N_UNIQUE_CHARS = 65
SEED = 42
DROPOUT = 0.2
N_TRANSFORMER_BLOCKS = 6
QUERY_SIZE = FEATURE_DIMS // N_TRANSFORMER_BLOCKS
DEBUG = False